### ISSUE TITLE
[wp][google][wiki]

### ISSUE THREAD

**Issue by Basic8** [FunctionalMetatable/BBCode-Cheatsheet#1]
Perhaps add these to your cheat sheet? These are useful tags.

**Comment by FunctionalMetatable** [comment]
@all-contributors please add @basic8 for documentation, ideas

**Comment by FunctionalMetatable** [comment]
@all-contributors please add @FunctionalMetatable for documentation, ideas

**Comment by FunctionalMetatable** [comment]
thank you!

**Comment by Basic8** [comment]
aa
